import sacrificePreview from "public/art/sacrifice-preview.webm";
import sacrificeFull from "public/art/sacrifice-full.webm";
import doctorWhoFull from "public/art/doctor-who-full.webm";
import doctorWhoPreview from "public/art/doctor-who-preview.webm";
import whenItFallsFull from "public/art/zero-7-when-it-falls-remix-full.webm";
import jojoPreview from "public/art/is-that-a-jojo-reference-preview.webm";
import jojoFull from "public/art/is-that-a-jojo-reference-full.webm";
import zaharaAlibiPreview from "public/art/zahara-alibi-promo-preview.webm";
import zaharaAlibiFull from "public/art/zahara-alibi-promo-full.webm";
import theGardenFull from "public/art/zero-7-the-garden-remix-full.webm";
import theGardenPreview from "public/art/zero-7-the-garden-remix-preview.webm";
import heirloomFull from "public/art/heirloom-full.webm";
import heirloomPreview from "public/art/heirloom-preview.webm";
import solAmuletFull from "public/art/sol-amulet-full.webm";
import solAmuletPreview from "public/art/sol-amulet-preview.webm";

export interface Media {
  still_url?: string;
  animation_preview?: string;
  animation_full?: string;
  youtube_id?: string;
  blurDataURL?: string;
}

export interface ArtProject {
  title: string;
  type: "animation" | "still" | "youtube";
  mediaCategory: string;
  description: string;
  created_at: string;
  updated_at: string;
  slug: string;
  featured: boolean;
  published_at: string;
  hash_id: string;
  permalink: string;
  tech: string[];
  featuredTech: string[];
  media: Media;
}

const data: ArtProject[] = [
  {
    title: "Sacrifice",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "🇺🇦 A dedication to the sacrifices made in Ukraine's fight for sovereignty. \n🕊 Created over several months starting shortly after the war began. It serves as a reminder that the world is still watching. What do you feel when you reflect on this?",
    created_at: "2022-05-22T15:29:42.800-05:00",
    updated_at: "2022-09-06T11:29:09.917-05:00",
    slug: "sacrifice",
    featured: true,
    published_at: "2022-05-22T15:29:42.787-05:00",
    hash_id: "3qQ9gB",
    permalink: "https://www.artstation.com/artwork/3qQ9gB",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPUlEQVR4nGNwNHf4//P/qwu3gqzdGLiZBR+fm//21joDRSMGGw29zrLMVdMqnPQtGLQlpY3VNIxU5cWYuQFQbRJTl2FZOQAAAABJRU5ErkJggg==",
      animation_preview: sacrificePreview,
      animation_full: sacrificeFull,
    },
  },
  {
    title: "Southern Freeway",
    type: "still",
    mediaCategory: "Digital Mixed Media",
    description:
      "A 3D extension of Hiroshi Nagai's 'Southern Freeway' (2017). Drawn to Nagai's vibrant colors and dreamy Americana, this piece is a remix of the original. Notably, the bush with red flowers was generated by DALL-E 2.",
    created_at: "2022-01-01T00:00:00.000-00:00", // replace with actual date
    updated_at: "2022-01-01T00:00:00.000-00:00", // replace with actual date
    slug: "southern-freeway",
    featured: false,
    published_at: "2022-08-30T00:00:00.000-00:00", // replace with actual date
    hash_id: "lDlJNz", // replace with actual value
    permalink: "https://www.artstation.com/artwork/lDlJNz", // replace with actual value
    tech: ["Blender", "DALL-E 2"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/ADKF9jWG+hl46SqA8QBzuf+M0f9GjccAGTAA1/P/yvH/qcjuAAwWAKmv0g8VJw0UJ3F6osKNGTBGNsLoAAAAAElFTkSuQmCC",
    },
  },
  {
    title: "Sacrifice II",
    type: "youtube",
    mediaCategory: "Digital Mixed Media",
    description:
      '"Sacrifice" - 3d Animation | Mixed Digital Media | Made with Blender \nIn dedication to the sacrifices made in Ukraine\'s fight for sovereignty.',
    created_at: "2021-01-24T21:26:49.679-06:00",
    updated_at: "2021-01-24T21:26:49.679-06:00",
    slug: "sacrifice-ii",
    featured: false,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.youtube.com/watch?v=MNdOG5oNWE8",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAT0lEQVR4nAFEALv/AEo/I/+ykWn/rY1j/y0jDv8AUDsb///uwv//47P/W0Mk/wBgSif/blg4/2VOLv9bRCb/ABoLAP9YQBz/WD4b/yASAP+XYiAh08EbiQAAAABJRU5ErkJggg==",

      youtube_id: "MNdOG5oNWE8",
    },
  },
  {
    title: "Zero 7 'The Garden' Remix",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "🌹A 3D animated remix of Zero 7's album art 'The Garden'. Modeled, textured, and animated in Blender, with video editing in DaVinci Resolve. This piece breathes life into static album art, reflecting the dynamic nature of music",
    created_at: "2021-10-20T12:33:22.906-05:00",
    updated_at: "2022-11-15T01:37:16.050-06:00",
    slug: "zero-7-the-garden-remix",
    featured: false,
    published_at: "2021-10-20T12:33:22.889-05:00",
    hash_id: "8eQZNG",
    permalink: "https://www.artstation.com/artwork/8eQZNG",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPUlEQVR4nGNQ0tIWEpdiYONk5uJhiIiPe/D61rr1y/0D/Riq6stffLr3+/97GycHBgYWVgY2bk5BIW4BIQCh8Q/RBM1HIwAAAABJRU5ErkJggg==",
      animation_preview: theGardenPreview,
      animation_full: theGardenFull,
    },
  },
  {
    title: "Zero 7 'When It Falls' Remix",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "A 3D take on Zero 7's album art for 'When It Falls'. Using various techniques, including converting the artwork into SVG and 3D meshes, this piece adds depth with compositing effects like chromatic aberration and film grain.",
    created_at: "2021-01-24T21:25:42.240-06:00",
    updated_at: "2021-03-27T22:20:55.764-05:00",
    slug: "zero-7-when-it-falls-remix",
    featured: true,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.artstation.com/artwork/rAKwGm",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/ABwAQSgCQl8yVSkBQwAUAD2veW7/5YebbGEAHAA75rSS//amonBjABoAP2I1VP/ntNKef6uTFDf0xBGQAAAAAElFTkSuQmCC",
      animation_preview: whenItFallsFull,
      animation_full: whenItFallsFull,
    },
  },
  {
    title: "Alterations - System Infinity EP Visuals",
    type: "youtube",
    mediaCategory: "Digital Mixed Media",
    description:
      "Visualizations for the 'System Infinity' EP by Alterations. Each track inspired a different narrative, meticulously modeled and animated in Blender, with the final piece produced in DaVinci Resolve 17.",
    created_at: "2021-01-24T21:25:42.240-06:00",
    updated_at: "2021-03-27T22:20:55.764-05:00",
    slug: "alterations-system-infinity-ep-visuals",
    featured: false,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.youtube.com/watch?v=iSqwFhvr_ys",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/AJSUgLHGlu7/xG53UQDcvbLivXXgzYBYQxUARiNQYjccU0lGGAAAAG9MjH9dhFlLVLGTgqLaFqbvg6/UAAAAAElFTkSuQmCC",
      youtube_id: "iSqwFhvr_ys",
    },
  },
  {
    title: "Zahara - Alibi Promo",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "A promotional render for singer Zahara's 'Alibi' single. This project involved both creating 3D promotional content and acting in the music video. Modeled and animated in Blender, with post-processing in DaVinci Resolve.",
    created_at: "2021-01-24T21:26:49.679-06:00",
    updated_at: "2021-01-24T21:26:49.679-06:00",
    slug: "zahara-alibi-promo",
    featured: true,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.artstation.com/artwork/LRlALK",
    tech: ["Blender", "Davinci Resolve"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPUlEQVR4nGOoSnCQY2dQFWUojbNnkGBhCDaXvL6mXVWalyHYSf/ricX/3+6tSAtiWDWpJNrPzsFEpa88DgB9shExz58zbgAAAABJRU5ErkJggg==",
      animation_preview: zaharaAlibiPreview,
      animation_full: zaharaAlibiFull,
    },
  },
  {
    title: "Is that... a JoJo reference?",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "A 3D model and animation of the Red Stone of Aja from JoJo’s Bizarre Adventure. The silver detail was generated using paint.net plugins to create normal and height maps from online images.",
    created_at: "2021-07-12T14:15:09.786-05:00",
    updated_at: "2021-12-08T19:01:04.628-06:00",
    slug: "is-that-a-jojo-reference",
    featured: true,
    published_at: "2021-07-12T14:15:09.766-05:00",
    hash_id: "nYznvo",
    permalink: "https://www.artstation.com/artwork/nYznvo",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAS0lEQVR4nBXGMQ5AQBRF0df4JiYS5rNclTWoLEans4EpdYhiVnDFqY4kYWakIfFfVYhs80ReF7o0ImsinBmOndD2yN0p90u5HmozPo0LH7rcvH20AAAAAElFTSuQmC",
      animation_preview: jojoPreview,
      animation_full: jojoFull,
    },
  },
  {
    title: "Sol Amulet",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "Praise the Sun! 🌞 Inspired by the Dark Souls series, this piece was modeled and animated in Blender. It celebrates the 'Praise the Sun' theme from the game.",
    created_at: "2021-06-03T20:53:04.341-05:00",
    updated_at: "2021-12-08T19:00:49.700-06:00",
    slug: "sol-amulet",
    featured: false,
    published_at: "2021-06-03T20:53:04.329-05:00",
    hash_id: "v2qrg6",
    permalink: "https://www.artstation.com/artwork/v2qrg6",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOElEQVR4nGNgZ2dnY2Xh5eFgZ2dnYGBgMDQ0MdAzArEYGBh+/vh/8PAjEIuVlTUtNj4hKoaZhRkArW0JKMO7SNgAAAAASUVORK5CYII=",
      animation_preview: solAmuletPreview,
      animation_full: solAmuletFull,
    },
  },
  {
    title: "Heirloom",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "A 3D tribute to a handcrafted guitar by Mark Swanson. The inlay and sound chamber cover are made from sustainably sourced abalone shell. This piece honors the instrument's significance in my family.",
    created_at: "2021-06-03T21:03:27.212-05:00",
    updated_at: "2021-07-17T14:26:59.824-05:00",
    slug: "heirloom",
    featured: false,
    published_at: "2021-06-03T21:03:27.184-05:00",
    hash_id: "D5Ry0G",
    permalink: "https://www.artstation.com/artwork/D5Ry0G",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/AEA7OEI9PiAYFaCVkABqa3n/+v/MtKTs3tYAX19y3MzPjFUkzaqTACQAAHlVTX5IIoNSOlD6FnlNuqaWAAAAAElFTkSuQmCC",
      animation_preview: heirloomPreview,
      animation_full: heirloomFull,
    },
  },
  {
    title: "Doctor Who?",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "A 3D animation inspired by Doctor Who, modeled and rendered using Blender. It captures the essence of the iconic series with detailed modeling and animation. ",
    created_at: "2021-01-27T18:39:09.028-06:00",
    updated_at: "2021-10-20T12:36:49.695-05:00",
    slug: "doctor-who",
    featured: false,
    published_at: "2021-01-27T18:39:09.018-06:00",
    hash_id: "9mQWOQ",
    permalink: "https://www.artstation.com/artwork/9mQWOQ",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      blurDataURL:
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/ALzH1cjQ3OXq8fr7/QCqr7W7wcior7m9wMUAMzc0QEZMAAsqAA0pAIiRnKywuwMvTRw6Uz+eGfLBwPbuAAAAAElFTkSuQmCC",
      animation_preview: doctorWhoPreview,
      animation_full: doctorWhoFull,
    },
  },
];

const sortedProjectsAZ = data.sort((a, b) => {
  if (a.title < b.title) {
    return -1;
  }
  if (b.title < a.title) {
    return 1;
  }
  return 0;
});

export default sortedProjectsAZ;
