import sacrificePreview from "public/art/sacrifice-preview.webm";
import sacrificeFull from "public/art/sacrifice-full.webm";
import doctorWhoFull from "public/art/doctor-who-full.webm";
import doctorWhoPreview from "public/art/doctor-who-preview.webm";
import whenItFallsFull from "public/art/zero-7-when-it-falls-remix-full.webm";
import jojoPreview from "public/art/is-that-a-jojo-reference-preview.webm";
import jojoFull from "public/art/is-that-a-jojo-reference-full.webm";
import zaharaAlibiPreview from "public/art/zahara-alibi-promo-preview.webm";
import zaharaAlibiFull from "public/art/zahara-alibi-promo-full.webm";
import theGardenFull from "public/art/zero-7-the-garden-remix-full.webm";
import theGardenPreview from "public/art/zero-7-the-garden-remix-preview.webm";
import heirloomFull from "public/art/heirloom-full.webm";
import heirloomPreview from "public/art/heirloom-preview.webm";
import solAmuletFull from "public/art/sol-amulet-full.webm";
import solAmuletPreview from "public/art/sol-amulet-preview.webm";

export interface Media {
  still_url?: string;
  animation_preview?: string;
  animation_full?: string;
  youtube_id?: string;
}

export interface ArtProject {
  title: string;
  type: "animation" | "still" | "youtube";
  mediaCategory: string;
  description: string;
  created_at: string;
  updated_at: string;
  slug: string;
  featured: boolean;
  published_at: string;
  hash_id: string;
  permalink: string;
  tech: string[];
  featuredTech: string[];
  media: Media;
}

const data: ArtProject[] = [
  {
    title: "Sacrifice",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "🇺🇦 In dedication to the sacrifices made in Ukraine's fight for sovereignty.⁣\n🕊 I started this piece a couple of days after the war started. Over these months I've chiseled at it here and there to end up at this point.\n💛 To publish this when the war is still evolving- and sacrifices are continuing to be made- is to call out that the world is still watching. I'm honored to be able to share this piece with this audience.⁣ What do you feel when you reflect on this?",
    created_at: "2022-05-22T15:29:42.800-05:00",
    updated_at: "2022-09-06T11:29:09.917-05:00",
    slug: "sacrifice",
    featured: true,
    published_at: "2022-05-22T15:29:42.787-05:00",
    hash_id: "3qQ9gB",
    permalink: "https://www.artstation.com/artwork/3qQ9gB",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: sacrificePreview,
      animation_full: sacrificeFull,
    },
  },
  {
    title: "Southern Freeway",
    type: "still",
    mediaCategory: "Digital Mixed Media",
    description:
      "This is my 3D extension of renowned Japanese illustrator/graphic designer Hiroshi Nagai's 'Southern Freeway' (2017).\n I was drawn to Nagai's use of vibrant colors and the dreamy Americana in his subject matter.\n While most of my pieces are original, this one is a heavily influenced remix from the original. This was the first time I tried to match the original composition 1-to-1 and then remix the elements from there. An interesting fact about this piece is that the bush with red flowers on the left side of the image was generated by DALL-E 2, a new AI system that can create realistic images and art from a description in natural language.\n\n I started this piece at the beginning of 2021, only a few months after figuring my way around Blender. Back then, I was constantly jumping from project to project to apply new techniques and imagine new concepts. This project fell off my list but I'm super happy to finally call it 'done'!",
    created_at: "2022-01-01T00:00:00.000-00:00", // replace with actual date
    updated_at: "2022-01-01T00:00:00.000-00:00", // replace with actual date
    slug: "southern-freeway",
    featured: false,
    published_at: "2022-08-30T00:00:00.000-00:00", // replace with actual date
    hash_id: "lDlJNz", // replace with actual value
    permalink: "https://www.artstation.com/artwork/lDlJNz", // replace with actual value
    tech: ["Blender", "DALL-E 2"],
    featuredTech: ["Blender"],
    media: {},
  },
  {
    title: "Sacrifice II",
    type: "youtube",
    mediaCategory: "Digital Mixed Media",
    description:
      '"Sacrifice" - 3d Animation | Mixed Digital Media | Made with Blender \nIn dedication to the sacrifices made in Ukraine\'s fight for sovereignty.',
    created_at: "2021-01-24T21:26:49.679-06:00",
    updated_at: "2021-01-24T21:26:49.679-06:00",
    slug: "sacrifice-ii",
    featured: false,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.youtube.com/watch?v=MNdOG5oNWE8",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      youtube_id: "MNdOG5oNWE8",
    },
  },
  {
    title: "Zero 7 'The Garden' Remix",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "🌹“The Garden” - 2021 - Modeled, textured, and animated in #Blender. Video edited in DaVinci Resolve.\n🎶 Back again with another album art remix from Zero 7… this time “The Garden”! There is just something about album art that leaves me wishing it was more than just a static image. So I gave this one the 3D treatment to bring it to life!\n🖼The original album art depicted a tear with a collage by Gideon London revealed underneath. To translate this into 3D meant painstakingly extracting each layer with Photoshop. With each layer now a separate piece in a stack, the pieces will look subtly different/askew depending on the camera perspective because of the variation in distance away from the lens.\nAdd some “dust” particles, a bit of movement, and a textured background that dynamically responds to light and 💥 BOOM ~ art ~\nHow does your music inspire you? Stay well, lovely people of the internet.",
    created_at: "2021-10-20T12:33:22.906-05:00",
    updated_at: "2022-11-15T01:37:16.050-06:00",
    slug: "zero-7-the-garden-remix",
    featured: false,
    published_at: "2021-10-20T12:33:22.889-05:00",
    hash_id: "8eQZNG",
    permalink: "https://www.artstation.com/artwork/8eQZNG",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: theGardenPreview,
      animation_full: theGardenFull,
    },
  },
  {
    title: "Zero 7 'When It Falls' Remix",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "This project is my 3D take on the album art from Zero 7's \"When It Falls\". The scene really comes together at Frame 50, where the original art lines up perfectly with my work. I used different tricks like converting the artwork into SVG and then turning those into 3D meshes to make this happen. \nTo give it a little extra something, I added some compositing effects like chromatic aberration and film grain. The original artwork is a piece from Blue Source Studios, but not much is known about them. With this piece, I've tried to keep the spirit of the original while putting my own spin on it. It's art meets music, in 3D.",
    created_at: "2021-01-24T21:25:42.240-06:00",
    updated_at: "2021-03-27T22:20:55.764-05:00",
    slug: "zero-7-when-it-falls-remix",
    featured: true,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.artstation.com/artwork/rAKwGm",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: whenItFallsFull,
      animation_full: whenItFallsFull,
    },
  },
  {
    title: "Alterations - System Infinity EP Visuals",
    type: "youtube",
    mediaCategory: "Digital Mixed Media",
    description:
      " 👾 Crafting visualizations for “System Infinity”, the third release in a trilogy of EPs from @Alterations, was a deep dive into the essence of music and animation.\n This journey entailed immersing myself in the tracks, wireframing their narratives, and playing the EP on repeat to truly grasp its core. Each listen inspired a facet of the story I aimed to depict.\n 🤖 The challenge and joy lay in bringing these auditory tales to life: surreal, contemplative, and wildly imaginative. Every element was meticulously modeled and animated in Blender, culminating in a final video piece seamlessly produced in DaVinci Resolve 17.",
    created_at: "2021-01-24T21:25:42.240-06:00",
    updated_at: "2021-03-27T22:20:55.764-05:00",
    slug: "alterations-system-infinity-ep-visuals",
    featured: false,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.youtube.com/watch?v=iSqwFhvr_ys",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      youtube_id: "iSqwFhvr_ys",
    },
  },
  {
    title: "Zahara - Alibi Promo",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "Promotional render for Zahara's Alibi single.\n This project holds a special place for me as I was not only involved in the creation of this 3D promotional content, but also had the opportunity to act in the music video. While on set, I was captivated by this particular phone, which I then photographed and used as a reference to model and animate in Blender 3. The post-processing was done mostly in Blender and then finished in Davinci Resolve.\n Zahara, being a friend of mine, made this project even more meaningful. I'm extremely pleased with how it turned out and consider it one of my favorite concepts yet.\n I'm always open to new projects, especially those that allow me to blend my interests and skills in unique ways. If you have a project that could benefit from some 3D work, let's talk!",
    created_at: "2021-01-24T21:26:49.679-06:00",
    updated_at: "2021-01-24T21:26:49.679-06:00",
    slug: "zahara-alibi-promo",
    featured: true,
    published_at: "2021-01-24T21:26:49.679-06:00",
    hash_id: "rAKwGm",
    permalink: "https://www.artstation.com/artwork/LRlALK",
    tech: ["Blender", "Davinci Resolve"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: zaharaAlibiPreview,
      animation_full: zaharaAlibiFull,
    },
  },
  {
    title: "Is that... a JoJo reference?",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "“Is that... a JoJo reference?” - 2021 - 3D, modeled and animated in Blender 🎭⁣⁣\n⁣⁣\nContinuing in the video game item theme, I wanted to bring to life the Red Stone of Aja from JoJo’s Bizarre Adventure. The detail of the silver was generated by some paint.net plugins for creating normal and height map images (tells the 3D software how to “fake” depth with clever lighting) from pictures found online. 🗿⁣⁣\n⁣⁣\nAs always, comments and criticism welcomed! ⁣",
    created_at: "2021-07-12T14:15:09.786-05:00",
    updated_at: "2021-12-08T19:01:04.628-06:00",
    slug: "is-that-a-jojo-reference",
    featured: true,
    published_at: "2021-07-12T14:15:09.766-05:00",
    hash_id: "nYznvo",
    permalink: "https://www.artstation.com/artwork/nYznvo",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: jojoPreview,
      animation_full: jojoFull,
    },
  },
  {
    title: "Sol Amulet",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "Praise the Sun! 🌞 \nModeled and animated in Blender 2.92.\nInspired by the item design in the Dark Souls series.",
    created_at: "2021-06-03T20:53:04.341-05:00",
    updated_at: "2021-12-08T19:00:49.700-06:00",
    slug: "sol-amulet",
    featured: false,
    published_at: "2021-06-03T20:53:04.329-05:00",
    hash_id: "v2qrg6",
    permalink: "https://www.artstation.com/artwork/v2qrg6",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: solAmuletPreview,
      animation_full: solAmuletFull,
    },
  },
  {
    title: "Heirloom",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "This one-of-a-kind guitar was hand crafted by a luthier named Mark Swanson for my pops (also named Mark Swanson). I grew up hearing this instrument and wanted to honor its role in the family. 🎸\nThe inlay and sound chamber cover are sustainably sourced abalone shell (from Kauai, I believe). Iridescence from the shell is incredibly difficult to get right in CG imagery but I think I managed it reasonably well here. 😎 I took a couple creative liberties here and there but its essence is retained.\nThe only assets that are not made from scratch are the rug (CC0), guitar stand(CC0), and clamps(Purchased) and some of the materials (CC0).",
    created_at: "2021-06-03T21:03:27.212-05:00",
    updated_at: "2021-07-17T14:26:59.824-05:00",
    slug: "heirloom",
    featured: false,
    published_at: "2021-06-03T21:03:27.184-05:00",
    hash_id: "D5Ry0G",
    permalink: "https://www.artstation.com/artwork/D5Ry0G",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: heirloomPreview,
      animation_full: heirloomFull,
    },
  },
  {
    title: "Doctor Who?",
    type: "animation",
    mediaCategory: "Digital Mixed Media",
    description:
      "“Doctor Who?” 2021 - Modeled, animated, rendered using Blender ✨👨‍⚕️ 🚀 ",
    created_at: "2021-01-27T18:39:09.028-06:00",
    updated_at: "2021-10-20T12:36:49.695-05:00",
    slug: "doctor-who",
    featured: false,
    published_at: "2021-01-27T18:39:09.018-06:00",
    hash_id: "9mQWOQ",
    permalink: "https://www.artstation.com/artwork/9mQWOQ",
    tech: ["Blender", "Davinci Resolve", "Photoshop"],
    featuredTech: ["Blender"],
    media: {
      animation_preview: doctorWhoPreview,
      animation_full: doctorWhoFull,
    },
  },
];

const sortedProjectsAZ = data.sort((a, b) => {
  if (a.title < b.title) {
    return -1;
  }
  if (b.title < a.title) {
    return 1;
  }
  return 0;
});

export default sortedProjectsAZ;
